apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml --namespace=hoeeeeeh --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
  namespace: hoeeeeeh
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  serviceName: prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/prometheus-grafana-default: "true"
        io.kompose.service: prometheus
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
          image: prom/prometheus
          name: prometheus
          ports:
            - containerPort: 9090
              hostPort: 9090
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-claim0
            - mountPath: /prometheus
              name: prom-data
      restartPolicy: Always
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: prometheus-claim0
        name: prometheus-claim0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: prom-data
        name: prom-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
status:
  availableReplicas: 0
  replicas: 0
